"""Add task field to WorkOrder model

Revision ID: 0c5c702b1796
Revises: d5ab06fc320a
Create Date: 2024-10-16 02:23:34.546257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5c702b1796'
down_revision = 'd5ab06fc320a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('task')

    # ### end Alembic commands ###
